# Generated by Django 3.2 on 2023-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
