# Generated by Django 3.2 on 2023-05-30 19:17

from django.db import migrations, models
import django.db.models.deletion
import lib.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.PositiveSmallIntegerField(choices=[(1, 'action'), (2, 'horror'), (5, 'si_fi'), (4, 'drama'), (3, 'comedy')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('recommended', models.BooleanField(default=True)),
                ('rate', models.PositiveSmallIntegerField(default=1, validators=[lib.validator.rate_validator])),
                ('description', models.TextField(blank=True, null=True)),
                ('times_rated', models.PositiveIntegerField()),
                ('imdb_rate', models.FloatField(default=1.0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='movie.moviegenre')),
            ],
        ),
    ]
