# Generated by Django 3.2 on 2023-05-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='times_rated',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
