# Generated by Django 3.2 on 2023-05-30 20:45

from django.db import migrations, models
import lib.validator


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_times_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rate',
            field=models.FloatField(default=1.0, validators=[lib.validator.rate_validator]),
        ),
    ]
