# Generated by Django 3.2 on 2023-05-30 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_alter_movie_imdb_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movie_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
