# Generated by Django 3.2 on 2023-05-30 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_user_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='next_allowed_modify',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 10, 7, 6, 533451)),
        ),
    ]
