# Generated by Django 3.2 on 2023-05-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20230530_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='next_allowed_modify',
        ),
        migrations.AddField(
            model_name='movie',
            name='total_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
