# Generated by Django 3.2 on 2023-05-31 03:43

from django.db import migrations, models
import lib.validator


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20230530_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(default=0, validators=[lib.validator.rate_validator]),
        ),
    ]
