# Generated by Django 3.2 on 2023-05-29 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('rate', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('times_watched', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('watch_list', models.BooleanField(blank=True, default=False, null=True)),
                ('recommended', models.BooleanField(blank=True, default=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
